INSERT INTO hibernate_sequences 
VALUES ('t_apply_req',10),
('t_bs_role',10),
('t_bs_user',10),
('t_debit_bid',10),
('t_field_survy',10),
('t_file',10),
('t_fund_flow',10),
('t_hc_inspect_log',10),
('t_hc_install_log',10),
('t_hc_merch_base_info',10),
('t_hc_trans',10),
('t_hc_trans_log',10),
('t_inst',10),
('T_INST_APPLY_REQ',10),
('t_inst_auth',10),
('t_inst_busi_info',10),
('t_inst_coll_merch',10),
('t_inst_coll_ord',10),
('t_inst_legal_pers',10),
('t_inst_notice',10),
('t_inst_role',10),
('t_inst_user',10),
('t_loanord_plan',10),
('t_loan_ord',10),
('t_loan_pdt',10),
('t_loan_pdt_his',10),
('t_loan_rpt',10),
('t_loan_statistics',10),
('t_merch',10),
('t_merch_busi_info',10),
('t_merch_coll_inst',10),
('t_merch_coll_pdt',10),
('t_merch_info_appeal',10),
('t_merch_info_perm',10),
('t_merch_legal_pers',10),
('t_merch_user',10),
('t_rpt_file',10),
('t_schedule',10),
('t_schedule_his',10),
('t_sms_log',10);


